/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.menagement.system.v2;

import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author User
 */
public class editemployees extends javax.swing.JFrame {

    /**
     * Creates new form editemployees
     */
    public editemployees() {
        initComponents();
        try {
           Connection conn = null;
             ResultSet rs = null;
            conn = dbconnection.connect();


          
           
          
            
        
            
            PreparedStatement statement = conn.prepareStatement("SELECT name, surname FROM workers ");
            ResultSet resultSet = statement.executeQuery();
             while (resultSet.next()) {
        String name = resultSet.getString("name");
        String surname = resultSet.getString("surname");
        String fullName = name + " " + surname;
        comboBox.addItem(fullName);
    }

    

    resultSet.close();
    statement.close();
    conn.close();
} catch (Exception e) {
    e.printStackTrace();
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        roleTextField = new javax.swing.JTextField();
        salaryTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, 30));

        jLabel3.setText("Surname:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 30));

        jLabel4.setText("Role:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 40, 30));

        jLabel5.setText("Salary:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, 30));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, 20));

        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(surnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 110, 20));
        getContentPane().add(roleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, -1));

        salaryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(salaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        jLabel6.setText("Start Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, -1));

        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 20, -1));

        startDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(startDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));
        getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 110, -1));

        jLabel8.setText("Select employee:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aleks" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/menagement/system/v2/My project-1 (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
     String selectedFullName = (String) comboBox.getSelectedItem();
        String selectedName = selectedFullName.split(" ")[0]; // Extract the name from the full name

        try {
           Connection conn = null;
            conn = dbconnection.connect();


            ResultSet rs = null;
           
          
            
        
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM workers WHERE name = ?");
            statement.setString(1, selectedName);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                String surname = resultSet.getString("surname");
                String role = resultSet.getString("role");
                int id = resultSet.getInt("id");
                double salary = resultSet.getDouble("salary");
                String startDate = resultSet.getString("start date");
                String name = resultSet.getString("name");
                
                nameTextField.setText(name);
                surnameTextField.setText(surname);
                roleTextField.setText(role);
                idTextField.setText(Integer.toString(id));
                salaryTextField.setText(Double.toString(salary));
                startDateTextField.setText(startDate);
            }

            resultSet.close();
            statement.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_comboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String selectedName = (String) comboBox.getSelectedItem();
        String updatedname = nameTextField.getText();
        String updatedSurname = surnameTextField.getText();
        String updatedRole = roleTextField.getText();
        int updatedId = Integer.parseInt(idTextField.getText());
        double updatedSalary = Double.parseDouble(salaryTextField.getText());
        
        // Retrieve other updated values from the text fields as needed

        try {Connection conn = null;
           conn = dbconnection.connect();
            PreparedStatement statement = conn.prepareStatement("UPDATE workers SET surname = ?, role = ?, id = ?, salary = ? WHERE name = ?");
            statement.setString(1, updatedSurname);
            statement.setString(2, updatedRole);
            statement.setInt(3, updatedId);
            statement.setDouble(4, updatedSalary);
            statement.setString(5, updatedname);

            int rowsAffected = statement.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("Data updated successfully.");
            } else {
                System.out.println("No changes made or worker not found.");
            }

            statement.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salaryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryTextFieldActionPerformed

    private void startDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editemployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editemployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editemployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editemployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editemployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField roleTextField;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JTextField surnameTextField;
    // End of variables declaration//GEN-END:variables
}
